definitions:
  domain.ApplicationData:
    properties:
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
      url:
        type: string
    type: object
  domain.ApplicationRequest:
    properties:
      created_at:
        type: string
      name:
        type: string
      updated_at:
        type: string
      url:
        type: string
    type: object
  domain.LogData:
    properties:
      created_at:
        type: string
      id:
        type: integer
      recipients:
        type: string
      request:
        type: string
      response:
        type: string
      source:
        type: string
      status_code:
        type: integer
      updated_at:
        type: string
    type: object
  domain.LogRequest:
    properties:
      created_at:
        type: string
      recipients:
        type: string
      request:
        type: string
      response:
        type: string
      source:
        type: string
      status_code:
        type: integer
      updated_at:
        type: string
    type: object
  domain.LogTopErrorData:
    properties:
      last_created_at:
        type: string
      last_id:
        type: string
      log_total:
        type: integer
      response:
        type: string
      source:
        type: string
    type: object
  domain.LogTotalData:
    properties:
      log_date:
        type: string
      log_total:
        type: integer
    type: object
  domain.PagingResponse:
    properties:
      data: {}
      page:
        type: integer
      per_page:
        type: integer
      total_data:
        type: integer
      total_page:
        type: integer
    type: object
  domain.Response:
    properties:
      data: {}
      elapsed_time:
        type: string
      message:
        type: string
    type: object
host: localhost:6969
info:
  contact:
    email: support@swagger.io
    name: ADE ARDIAN
    url: http://www.swagger.io/support
  description: LOGGING SYSTEM API SERVICE
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: API SWAGGER FOR LOGGING SYSTEM API SERVICE
  version: 1.0.0
paths:
  /api/v1/application:
    post:
      consumes:
      - application/json
      description: Create Application
      parameters:
      - description: ' ApplicationRequest Schema '
        in: body
        name: ApplicationRequest
        required: true
        schema:
          $ref: '#/definitions/domain.ApplicationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/domain.Response'
            - properties:
                data:
                  $ref: '#/definitions/domain.ApplicationData'
              type: object
      summary: Create Application
      tags:
      - Application
  /api/v1/log:
    get:
      consumes:
      - application/json
      description: Get All Log
      parameters:
      - in: query
        name: created_at
        type: string
      - in: query
        name: end_date
        type: string
      - in: query
        name: limit
        type: integer
      - in: query
        name: order_by
        type: string
      - in: query
        name: page
        type: integer
      - in: query
        name: recipients
        type: string
      - in: query
        name: request
        type: string
      - in: query
        name: response
        type: string
      - in: query
        name: sort_by
        type: string
      - in: query
        name: source
        type: string
      - in: query
        name: start_date
        type: string
      - in: query
        name: status_code
        type: integer
      - in: query
        name: updated_at
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/domain.Response'
            - properties:
                data:
                  allOf:
                  - $ref: '#/definitions/domain.PagingResponse'
                  - properties:
                      data:
                        items:
                          $ref: '#/definitions/domain.LogData'
                        type: array
                    type: object
              type: object
      summary: Get All Log
      tags:
      - Log
    post:
      consumes:
      - application/json
      description: Create Log
      parameters:
      - description: ' LogRequest Schema '
        in: body
        name: LogRequest
        required: true
        schema:
          $ref: '#/definitions/domain.LogRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/domain.Response'
            - properties:
                data:
                  $ref: '#/definitions/domain.LogData'
              type: object
      summary: Create Log
      tags:
      - Log
  /api/v1/log/{log_id}:
    get:
      consumes:
      - application/json
      description: Get Detail Log
      parameters:
      - description: ' Log Id '
        in: path
        name: log_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/domain.Response'
            - properties:
                data:
                  $ref: '#/definitions/domain.LogData'
              type: object
      summary: Get Detail Log
      tags:
      - Log
  /api/v1/log/range:
    get:
      consumes:
      - application/json
      description: Get All Log By Range
      parameters:
      - in: query
        name: created_at
        type: string
      - in: query
        name: end_date
        type: string
      - in: query
        name: limit
        type: integer
      - in: query
        name: order_by
        type: string
      - in: query
        name: page
        type: integer
      - in: query
        name: recipients
        type: string
      - in: query
        name: request
        type: string
      - in: query
        name: response
        type: string
      - in: query
        name: sort_by
        type: string
      - in: query
        name: source
        type: string
      - in: query
        name: start_date
        type: string
      - in: query
        name: status_code
        type: integer
      - in: query
        name: updated_at
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/domain.Response'
            - properties:
                data:
                  $ref: '#/definitions/domain.LogTotalData'
              type: object
      summary: Get All Log By Range
      tags:
      - Log
  /api/v1/log/top:
    get:
      consumes:
      - application/json
      description: Get Top Error Log
      parameters:
      - in: query
        name: created_at
        type: string
      - in: query
        name: end_date
        type: string
      - in: query
        name: limit
        type: integer
      - in: query
        name: order_by
        type: string
      - in: query
        name: page
        type: integer
      - in: query
        name: recipients
        type: string
      - in: query
        name: request
        type: string
      - in: query
        name: response
        type: string
      - in: query
        name: sort_by
        type: string
      - in: query
        name: source
        type: string
      - in: query
        name: start_date
        type: string
      - in: query
        name: status_code
        type: integer
      - in: query
        name: updated_at
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/domain.Response'
            - properties:
                data:
                  $ref: '#/definitions/domain.LogTopErrorData'
              type: object
      summary: Get Top Error Log
      tags:
      - Log
swagger: "2.0"
